export enum Environment {
  ENVIRONMENT = 'ENVIRONMENT',

  PORT = 'PORT',

  COGNITO_USER_POOL_ID = 'COGNITO_USER_POOL_ID',
  COGNITO_CLIENT_ID = 'COGNITO_CLIENT_ID',
  COGNITO_REGION = 'COGNITO_REGION',

  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_REGION = 'AWS_REGION',
}
